name: 'virtme-ng Action'
description: 'Run CI workloads inside a virtme-ng VM with a specific kernel'

branding:
  icon: 'cpu'
  color: 'orange'

inputs:
  name:
    description: 'Name for the kernel build cache (e.g., my-project-kernel)'
    required: true
  kernel-url:
    description: 'Git repository URL for the kernel source'
    required: true
  kernel-tag:
    description: 'Git tag or branch to checkout (e.g., v6.12, master)'
    required: true
  version:
    description: 'Cache version string, bump to invalidate the cache (e.g., v1, v2)'
    required: false
    default: 'v2'
  kconfig:
    description: 'Path to a kconfig fragment file (relative to the repo root)'
    required: false
    default: ''
  cpus:
    description: 'Number of CPUs for the VM (default: all host CPUs)'
    required: false
    default: ''
  memory:
    description: 'Memory for the VM, e.g. 4G, 512M (default: 90% of host RAM)'
    required: false
    default: ''
  network:
    description: 'Network mode for the VM, e.g. user (default: none)'
    required: false
    default: ''
  verbose:
    description: 'Enable verbose vng boot output'
    required: false
    default: 'true'
  cc:
    description: 'C compiler for the kernel build (e.g., clang)'
    required: false
    default: ''
  llvm:
    description: 'Use the full LLVM toolchain (CC=clang, LD=ld.lld, AR=llvm-ar, etc.)'
    required: false
    default: ''
  kernel-compile-cache:
    description: 'Use ccache to speed up kernel rebuilds on cache miss (default: true)'
    required: false
    default: 'true'
  deps-timeout:
    description: 'Timeout in seconds for dependency installation (per attempt)'
    required: false
    default: '90'
  deps-retries:
    description: 'Number of retry attempts for dependency installation'
    required: false
    default: '3'
  append:
    description: 'Additional kernel boot parameters passed to vng via --append'
    required: false
    default: 'mitigations=off'
  qemu-opts:
    description: 'Additional QEMU options passed to vng via --qemu-opts'
    required: false
    default: '-cpu host'
  run-timeout:
    description: 'Timeout in seconds for the VM workload (0 = no timeout)'
    required: false
    default: '0'
  packages:
    description: 'Extra apt packages to install and cache alongside vng dependencies (space-separated)'
    required: false
    default: ''
  install-recommends:
    description: 'Install recommended packages alongside dependencies (default: false)'
    required: false
    default: 'false'
  extra-rwdirs:
    description: 'Additional host directories to mount read-write in the VM (space-separated, tilde-expanded)'
    required: false
    default: '~/.cargo'
  run:
    description: 'Commands to execute inside the VM'
    required: true

outputs:
  kernel-sha:
    description: 'Short commit SHA (12 chars) of the resolved kernel commit'
    value: ${{ steps.kernel-sha.outputs.sha }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      env:
        VNG_NAME: ${{ inputs.name }}
        VNG_KERNEL_URL: ${{ inputs.kernel-url }}
        VNG_KERNEL_TAG: ${{ inputs.kernel-tag }}
        VNG_RUN: ${{ inputs.run }}
        VNG_KCONFIG: ${{ inputs.kconfig }}
      run: |
        errors=0
        if [ -z "$VNG_NAME" ]; then
          echo "::error::Input 'name' is required but was not provided."
          errors=$((errors + 1))
        fi
        if [ -z "$VNG_KERNEL_URL" ]; then
          echo "::error::Input 'kernel-url' is required but was not provided."
          errors=$((errors + 1))
        fi
        if [ -z "$VNG_KERNEL_TAG" ]; then
          echo "::error::Input 'kernel-tag' is required but was not provided."
          errors=$((errors + 1))
        fi
        if [ -z "$VNG_RUN" ]; then
          echo "::error::Input 'run' is required but was not provided."
          errors=$((errors + 1))
        fi
        if [ -n "$VNG_KCONFIG" ] && [ ! -f "$GITHUB_WORKSPACE/$VNG_KCONFIG" ]; then
          echo "::error::kconfig file not found: '$VNG_KCONFIG' (resolved to '$GITHUB_WORKSPACE/$VNG_KCONFIG')"
          errors=$((errors + 1))
        fi
        if [ "$errors" -gt 0 ]; then
          exit 1
        fi

    - name: Fix apt cache permissions for restore
      shell: bash
      run: sudo chown -R "$(id -u):$(id -g)" /var/cache/apt/archives

    - name: Restore apt cache
      id: apt-cache
      uses: actions/cache/restore@v4
      with:
        path: /var/cache/apt/archives
        key: vng-apt-${{ runner.arch }}-${{ github.run_id }}
        restore-keys: vng-apt-${{ runner.arch }}-

    - name: Restore apt cache ownership
      shell: bash
      run: sudo chown -R root:root /var/cache/apt/archives

    - name: Install dependencies
      shell: bash
      run: bash "${{ github.action_path }}/scripts/install-deps.sh"
      env:
        VNG_DEPS_TIMEOUT: ${{ inputs.deps-timeout }}
        VNG_DEPS_RETRIES: ${{ inputs.deps-retries }}
        VNG_EXTRA_PACKAGES: ${{ inputs.packages }}
        VNG_INSTALL_RECOMMENDS: ${{ inputs.install-recommends }}

    - name: Save apt cache
      if: steps.apt-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo rm -f /var/cache/apt/archives/lock
        sudo rm -rf /var/cache/apt/archives/partial
        sudo chown -R "$(id -u):$(id -g)" /var/cache/apt/archives
    - uses: actions/cache/save@v4
      if: steps.apt-cache.outputs.cache-hit != 'true'
      with:
        path: /var/cache/apt/archives
        key: vng-apt-${{ runner.arch }}-${{ github.run_id }}

    - name: Restore kernel SHA from prior job
      id: sha-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: .vng-sha-${{ inputs.name }}
        key: vng-sha-${{ inputs.name }}-${{ inputs.kernel-tag }}-${{ github.run_id }}

    - name: Resolve kernel commit SHA
      id: kernel-sha
      shell: bash
      run: |
        SHA_FILE="$GITHUB_WORKSPACE/.vng-sha-${{ inputs.name }}/sha"

        # Use cached SHA from a prior job in this run
        if [ -f "$SHA_FILE" ]; then
          SHA=$(cat "$SHA_FILE")
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
          echo "Using cached kernel SHA from prior job: $SHA"
          exit 0
        fi

        # For annotated tags, ls-remote returns both the tag object and the
        # dereferenced commit (tagged ^{}). Prefer the dereferenced commit
        # so we always resolve to the same underlying commit SHA.
        REMOTE_OUTPUT=""
        for attempt in 1 2 3; do
          REMOTE_OUTPUT=$(git ls-remote "${{ inputs.kernel-url }}" "${{ inputs.kernel-tag }}" "${{ inputs.kernel-tag }}^{}" 2>/dev/null || true)
          if [ -n "$REMOTE_OUTPUT" ]; then
            break
          fi
          if [ "$attempt" -lt 3 ]; then
            echo "::warning::git ls-remote attempt $attempt/3 failed, retrying in 5s..."
            sleep 5
          fi
        done
        if [ -z "$REMOTE_OUTPUT" ]; then
          echo "::warning::Could not resolve ref '${{ inputs.kernel-tag }}' from ${{ inputs.kernel-url }}, will try stale cache"
          echo "sha=" >> "$GITHUB_OUTPUT"
          echo "remote_failed=true" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        # Take ^{} (dereferenced) line if present, otherwise the direct ref
        DEREF=$(echo "$REMOTE_OUTPUT" | { grep '\^{}' || true; } | awk '{print $1}')
        DIRECT=$(echo "$REMOTE_OUTPUT" | { grep -v '\^{}' || true; } | awk '{print $1}')
        FULL_SHA="${DEREF:-$DIRECT}"
        SHA="${FULL_SHA:0:12}"

        # Write SHA to file for cross-job propagation
        mkdir -p "$GITHUB_WORKSPACE/.vng-sha-${{ inputs.name }}"
        echo -n "$SHA" > "$SHA_FILE"

        echo "sha=$SHA" >> "$GITHUB_OUTPUT"
        echo "remote_failed=false" >> "$GITHUB_OUTPUT"
        echo "Resolved ${{ inputs.kernel-tag }} -> $SHA"

    - name: Save kernel SHA for subsequent jobs
      if: steps.sha-cache-restore.outputs.cache-hit != 'true' && steps.kernel-sha.outputs.sha != ''
      uses: actions/cache/save@v4
      with:
        path: .vng-sha-${{ inputs.name }}
        key: vng-sha-${{ inputs.name }}-${{ inputs.kernel-tag }}-${{ github.run_id }}

    - name: Restore kernel build cache
      if: steps.kernel-sha.outputs.sha != ''
      uses: actions/cache/restore@v4
      id: kernel-cache
      with:
        path: linux
        key: vng-kernel-${{ inputs.name }}-${{ runner.arch }}-${{ steps.kernel-sha.outputs.sha }}-${{ inputs.version }}

    - name: Fallback to most recent cached kernel
      if: steps.kernel-sha.outputs.remote_failed == 'true'
      id: stale-cache
      uses: actions/cache/restore@v4
      with:
        path: linux
        key: vng-kernel-${{ inputs.name }}-${{ runner.arch }}-impossible-key-to-force-prefix-match
        restore-keys: |
          vng-kernel-${{ inputs.name }}-${{ runner.arch }}-

    - name: Verify stale cache fallback
      if: steps.kernel-sha.outputs.remote_failed == 'true'
      shell: bash
      run: |
        if [ ! -d linux ] || [ ! -f linux/.config ]; then
          echo "::error::Remote unreachable and no cached kernel found for ${{ inputs.name }}"
          exit 1
        fi
        echo "::warning::Using stale cached kernel for ${{ inputs.name }} (remote was unreachable)"

    - name: Restore ccache
      if: steps.kernel-cache.outputs.cache-hit != 'true' && inputs.kernel-compile-cache == 'true'
      uses: actions/cache/restore@v4
      id: ccache-restore
      with:
        path: ~/.cache/ccache
        key: vng-ccache-${{ runner.arch }}-${{ github.run_id }}
        restore-keys: vng-ccache-${{ runner.arch }}-

    - name: Clone and build kernel
      if: steps.kernel-cache.outputs.cache-hit != 'true' && steps.kernel-sha.outputs.remote_failed != 'true'
      shell: bash
      run: bash "${{ github.action_path }}/scripts/build-kernel.sh"
      env:
        VNG_KERNEL_URL: ${{ inputs.kernel-url }}
        VNG_KERNEL_TAG: ${{ inputs.kernel-tag }}
        VNG_KERNEL_NAME: ${{ inputs.name }}
        VNG_KCONFIG: ${{ inputs.kconfig }}
        VNG_KERNEL_DIR: ${{ github.workspace }}/linux
        VNG_CC: ${{ inputs.cc }}
        VNG_LLVM: ${{ inputs.llvm }}
        VNG_CCACHE: ${{ inputs.kernel-compile-cache }}

    - name: Save kernel build cache
      if: steps.kernel-cache.outputs.cache-hit != 'true' && steps.kernel-sha.outputs.remote_failed != 'true' && steps.kernel-sha.outputs.sha != ''
      uses: actions/cache/save@v4
      with:
        path: linux
        key: vng-kernel-${{ inputs.name }}-${{ runner.arch }}-${{ steps.kernel-sha.outputs.sha }}-${{ inputs.version }}

    - name: Save ccache
      if: steps.kernel-cache.outputs.cache-hit != 'true' && steps.kernel-sha.outputs.remote_failed != 'true' && inputs.kernel-compile-cache == 'true'
      uses: actions/cache/save@v4
      with:
        path: ~/.cache/ccache
        key: vng-ccache-${{ runner.arch }}-${{ github.run_id }}

    - name: Run workload in VM
      shell: bash
      run: bash "${{ github.action_path }}/scripts/run-workload.sh"
      env:
        VNG_COMMANDS: ${{ inputs.run }}
        VNG_KERNEL_DIR: ${{ github.workspace }}/linux
        VNG_CPUS: ${{ inputs.cpus }}
        VNG_MEMORY: ${{ inputs.memory }}
        VNG_NETWORK: ${{ inputs.network }}
        VNG_VERBOSE: ${{ inputs.verbose }}
        VNG_RUN_TIMEOUT: ${{ inputs.run-timeout }}
        VNG_EXTRA_RWDIRS: ${{ inputs.extra-rwdirs }}
        VNG_APPEND: ${{ inputs.append }}
        VNG_QEMU_OPTS: ${{ inputs.qemu-opts }}
